version: '3'
services:
  app:
    container_name: sso
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CONFIG_PATH=/app/config/prod.yaml
    ports:
      - '6868:6868'
    networks:
      - sso
networks:
  sso:
    driver: bridge