version: '3'

tasks:
  migrations:
    desc: "DB migrations"
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations
  test-migrations:
    desc: "tests DB migrations"
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./tests/migrations --migrations-table=migrations_test
  run-dev:
    desc: "run app"
    cmds:
      - go run ./cmd/sso --config=./config/dev.yaml