version: '3'

tasks:
  migrations:
    desc: "DB migrations"
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations
  test-migrations:
    desc: "tests DB migrations"
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./tests/migrations --migrations-table=migrations_test
  dev:
    desc: "run app in dev mode"
    cmds:
      - go run ./cmd/sso --config=./config/dev.yaml
  tests:
    desc: "run tests"
    cmds:
      - go test .\tests
  docker:
    desc: "run in docker"
    cmds:
      - docker-compose up --build